safe: false
incremental: true
lsi: false

exclude: [
  '.*',
  '_config.yml',
  '*.sublime*',
  'Gemfile',
  'Gemfile.lock',
  's3_website.yml',
  'README.md'
]

sass:
  style: :compressed
  load_paths:
    - _sass
    - node_modules

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
