safe: false
lsi: false

exclude: [
  '.*',
  '*.sublime*',
  'Gemfile',
  'Gemfile.lock',
  's3_website.yml',
  'README.md'
]

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
